---
- name: service | Configuring Loki Service
  ansible.builtin.template:
    src: etc/systemd/system/loki.service.j2
    dest: /etc/systemd/system/loki.service
    mode: u=rw,g=r,o=r
  notify:
    - reload systemd
    - restart loki
  become: true
  when: ansible_service_mgr == "systemd"

- name: service | Ensuring Loki Service Is Started and Enabled
  ansible.builtin.service:
    name: loki
    state: started
    enabled: true
  become: true
